---
name: MLT Render Workflow

on:
  push:
    paths:
      - 'assets/**'  # Trigger workflow on any changes in the assets folder
      - '.github/workflows/ci.yml'  # Trigger workflow when the ci.yml file changes
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions UI

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # This checks out your repository

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y melt ffmpeg xvfb python3

      - name: Run doit.py to update MLT file
        run: |
          python3 scripts/doit.py  # Assuming doit.py is located in the scripts folder

      - name: Check if MLT file was generated
        run: ls -l assets/mlt/updated_video_as_code.mlt

      - name: Set LADSPA_PATH
        run: export LADSPA_PATH=""

      - name: Run MLT Rendering
        run: |
          xvfb-run -a melt assets/mlt/updated_video_as_code.mlt \
          -consumer avformat:outputs/final_video.mp4 \
          acodec=aac vcodec=libx264 crf=23 preset=slow fflags=+genpts

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit MP4 to the repository
        run: |
          git fetch origin main
          git add outputs/final_video.mp4  # Only add the final MP4 file
          git commit -m "Add/update mp4: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
